#coding: utf-8
# 共通
defaults: &defaults
  PH_LIMIT_INDEX_PHRASE_NUM: 5 # 一覧表示するフレーズ数のリミット

# example)
#  hoge_number:
#    min: 1
#    max: 99

  MENSEKI:
    'サービス提供について': '当サイトは、ユーザーへの通知なしに、掲載情報の内容およびその提供方法、ならびに当サイトにおいて提供する各種付加機能を変更し、またはこれらの提供を停止することがあります。これによりユーザーに損害が生じた場合であっても、当サイトはその責任を負いません。'
    'コンテンツの内容について': '当サイトは、当サイトの掲載情報（広告・他社サービスを含む）・各種付加機能の正確性、信頼性、有益性その他の事項について保証せず、ユーザーがそれらの情報を利用した結果について一切責任を負いません。'
    '障害について': '当サイトは、ユーザーが当サイトの利用中に発生した不具合、エラー、障害等により本サービスが利用できないことによって引き起こされた損害について一切の賠償責任を負いません。'

# 開発環境用
development:
  <<: *defaults

# テスト環境用
test:
  <<: *defaults

# 本番環境用
production:
  <<: *defaults